# Site settings
baseURL = ""
languageCode = "es-ES"
title = "Natalia"
#theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2019"

[params]

  # Metadata for search engines and social sharing
  author = "Natalia Pineda"
  description = "Cantante hondureña de rock y covers"
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"
  facebook = "natalia.pineda.9619"
  instagram = "natalia"
  itsky = "https://facebook.com/itskyapps"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "/images/actress.jpg"
      position = "center center"
      

    # Video main
    [params.visual.video]
      enable = false
      mute = true
      file = "/videos/background.mp4"
      #youtubeId = "dk9uNWPP7EA"
      youtubeCont = "aNcQJgHv2hQ"

    
  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "#"

      [[params.links.list1.link]]
        text = "Email"
        url = "#"

      [[params.links.list1.link]]
        text = "Newsletter"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Redes Sociales"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "/"

      [[params.links.list2.link]]
        text = "Youtube"
        url = "/"

  # Links List 
#  [[params.links]]
#    [params.links.list3]
#      heading = "Network"

#      [[params.links.list3.link]]
#        text = "Link One"
#        url = "#"

 #     [[params.links.list3.link]]
 #       text = "Link Two"
 #       url = "#"

 #     [[params.links.list3.link]]
 #       text = "Link Three"
 #       url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

